name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: yarn install
        run: yarn install --frozen-lockfile --link-duplicates --silent;
      - name: yarn lint
        run: yarn lint
      - name: yarn test
        run: yarn test:related
